/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    PlayerSingin: typeof import('./components/PlayerSingin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScouterSingin: typeof import('./components/ScouterSingin.vue')['default']
    Singin: typeof import('./components/Singin.vue')['default']
  }
}
